### ISSUE TITLE
error: 'VERSION' undeclared (first use in this function)

### ISSUE THREAD

**Issue by somefunAgba** [Ro5bert/avra#22]
There is an error when building from source on Windows.

**file.c:98:11:** _error: 'VERSION' undeclared (first use in this function)
           VERSION, basename, ctime(&pi->time));_
**file.c:98:11:** _note: each undeclared identifier is reported only once for each function it appears in
macro.c: In function 'expand_macro'_

I was able to resolve this by adding the following to **avra.h**
```
#ifndef VERSION
#define VERSION "undefined"
#endif
```
Saw that the above was defined in **avra.c**. Placing it in **avra.h** solved the problem.

I guess it would be helpful for others, if this was rectified in the main code base.

**Comment by Ro5bert** [comment]
I'm not sure what you mean by "[build] without using the Makefile". Did you manually invoke the compiler and linker? If so, that would explain the error with `VERSION`.

Currently, to build on a given OS `x`, you should execute `make OS=x` (unless `x`=linux, which is the default). You may also have to change your compiler: `make OS=x CC=mycompiler`. The supported OS's can be found in the `src/makefiles` directory as `Makefile.x` files. You mentioned trying `OS=mingw`, but that's not a supported OS; maybe try `OS=mingw32` instead. The mingw32 makefile was recently reported as working.
